export const maps = {
  a_1:
    "12-10-15;" +
    "tttttttttttttttttttttttttttttttttttttttt" +
    "txxxxxxcxxdxbcxxxxxbxbxxxxxxxcxxxxbxxxxt" +
    "txbsbxxxxxxcxxxxxxxxxbdxxbxxxxcxxxxxcxxt" +
    "txxxxxxxxxxcxxbxxxxxbxbxxbxxxxxxxxbxxxxt" +
    "tbxbbxxxxxxxxxbxxxxxxbxxbxxxxbxxxbxxxxxt" +
    "tbxcbxxxxxxxxxcbxxbxxxxxxxxbxxxxxxbxbbxt" +
    "txxxcxxbxxxxxxxxbxxxxxbxcbxxxxxxxxbxbbxt" +
    "twwwwwwwwwwwwwwwwwwwwwwwwwwwwwwxxxbxxbxt" +
    "txcxxxbxxdxcxxbxbxxxxxxxxxxdxbdxxxxxxcxt" +
    "txxdxxxxxbxxxxxcxxxxxxxxbbcbxxbxxxxbxxxt" +
    "txxxbxxbxbxxxxxxxxxxxxxxbcxbxxbxxxxxxxxt" +
    "txbxxxxxbxxxxxxxxbbbxxxxxxxbxxcxdxxxxbxt" +
    "txdxxcxxbxccxxxxxbxbdxxdxxxxbxxxbxxdxcxt" +
    "txcbxxxxxxxxxxxxxxbcbxxbxxxxxxxxdxxxxxbt" +
    "txxxxxxxxwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwt" +
    "tcbxxxxxxxxxbxxxdxxxxbxxxxxbxxxbxxxxxxxt" +
    "tcbxxxxxxxxxcbxxbxxxxxxxxbxxxxxxbxbbxxet" +
    "txcxxbxxxxxxxxbxxxxxbxccxxxxdxxxbxbbxxxt" +
    "txxxxbdxxbxxxxxxxxbxxxxxxbxbdxxxxxxbxxxt" +
    "txxxcxxbxcxxbxbbxxxxxxxxxbxbdxxxxxxcxxbt" +
    "txdxxxxcxxxxxcxxxxxxxxxcxbxxbxxxxbxxxbxt" +
    "tttttttttttttttttttttttttttttttttttttttt",
  b_1:
    "10-20-50;" +
    "tttttttttttttttttttttttttttttttttttttttt" +
    "txbxxbxxwxbxxxdxwxxxcxbxwbxxxxxxwxxbbxxt" +
    "txxxxxxxwxxxxxxbwbbxcxxxwcxxdxxxwxxxxbxt" +
    "tcccccccccccccccccccccccccccccccccccccct" +
    "tdxxxxxxwxbxxxxbwxbxcxxcwxxbxxdxwxxbxbxt" +
    "txxxxxxxwxbxxxxbwxbxcbxxwxxxxxbxwxxxcxxt" +
    "twwwwwwwwwwwwwwwwwwwcwwwwwwwwwwwwwwwwwwt" +
    "txxxxbbxwxxbxxxxwxxxcxxbwxxxxbxxwxxxxxbt" +
    "txxxxxxxwxxcxxxxwxxxcxxxwxxxxbxcwxxxxxbt" +
    "tcccccccccccccccccccccccccccccccccccccct" +
    "tbxxbxxxwxxxxbxxwxxbcxxxwxxxxxxdwbxxxxxt" +
    "tbxxxxbxwxxbxxbxwxxxcxcbwxxxxxxxwbxxxbxt" +
    "txbxxxxxwxxxbxxxwxxxcxcbwxxxxxxxwcbxxbxt" +
    "twwwwwwwwwwwwwwwwwwwcwwwwwwwwwwwwwwwwwwt" +
    "tbxccfxxwxxxxbxbwxxxcxxxwxbdxxbxwxxxxxxt" +
    "txxxxxbxwbxxxxxxwxxdcxxxwcxxbxxxwxbxbbxt" +
    "tcccccccccccccccccccccccccccccccccccccct" +
    "tdxxcxbxwbxxxxbxwxbxcxxbwxbxbxxxwxxxxxxt" +
    "txxxxxbxwbxxdxxxwxxxcbxxwxxbxxxxwxxxbbct" +
    "txdxxxcbwxxbxxxxwxsdcbxxwxcxxxxxwxxxbbct" +
    "txbxxxxcwxxcxxbxwxexcxxxwxxxxbxbwxxxxcxt" +
    "tttttttttttttttttttttttttttttttttttttttt",
  c_1:
    "24-15-0;" +
    "tttttttttttttttttttttttttttttttttttttttt" +
    "txxbxxxxxwxxbxwxxxwwbxxwxdxxxwbxxbxbxxxt" +
    "twbsxxxxxwxxbxwxdxxxxbxwwxxbxwwbxxxxxxxt" +
    "twbxxxxxxwxxwbxxbxxxxwxxxbxxxxxxbxbbxxxt" +
    "txwxxbxwxxxwxxbxwwxxbxwwxxxwxxxxbxbbxxxt" +
    "txwxxbdxxbxxxxwxxxbxxxxxxbxbdxxxxxxbxxxt" +
    "txxwbxxdxwxxbxbbxxxwxxxxxbxbdxxxxxxwxxbt" +
    "tdxdxbwxbxxxxwxwwxxxxxbbwbxxbxwxwbxxwbxt" +
    "twbxxbxbxxxxwxwwxxxxxxbwwbxxbxxxwwxxxwxt" +
    "txwwxxbxwwxxxxwbbbxwxxxwwbxxwxdxxxwbxxxt" +
    "txxwxxbxwwxxxxxbxbdxxdxwxwbxxwbxxdxwxxbt" +
    "tbxxxxwxxxxxwxxwbwbxxbxxxxwxxxdxxxwxbwxt" +
    "txxxwxwwddbxwxxxwwbxxwxbxxxwbxxbxbxxxwxt" +
    "txxxxxxwxxbxwxdxxxxbxwwxxbxwwbxxxxxxxbxt" +
    "txxxxxxwxxwbxxbxxxxwxxxbxxxxxxbxbbxxxxxt" +
    "txxbxwxxxwxxbxwwxxbxwwxxxwdxxxbxbbxxxxxt" +
    "txxbdxxbxxxxwxxxbxxxxxxbxbdxxxxxxbxxxwwt" +
    "txwxxbxwxxbxbbxxxwxxxxxbxbdxxxxxxwxxbxwt" +
    "txxxxwxxxxxwxwwxxxxxxwwbxxbxwxwbxxwbxxxe" +
    "txxbxbxxxxwxwwxxxxxxxwwbxxbxxdwwxxxwxxbt" +
    "twxxbxwwxxxxwbbbdxxdxwxwbxxwbwxxwbxxdwbt" +
    "tttttttttttttttttttttttttttttttttttttttt",
  d_1:
    "36-5-20;" +
    "tttttttttttttttttttttttttttttttttttttttt" +
    "tsxxxxxbxxxxxxxxxxxxxxxxxxxxbxxxxxxxxbxt" +
    "txxxxxbxxxxxxxxxxxxxxbxxxxxxxxxxxxxxxxxt" +
    "txxxxxxxxbxxbxxxxxxxxxxxxxxxxxxxxxxxxxxt" +
    "tbxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxt" +
    "txxxxxxxxxxxxxxxxxxxbxxxxxxxxxxxxxxxxxxt" +
    "txbxxxxxxxxxxxxxxxxxxxxxbxxxxxxxxxbxxxxt" +
    "txxbxxxxxbxxxxxxxxxxxbxxbxxxxxxxxxxxxxbt" +
    "txxxxxxbxxxxxxbxxxxxxxxxxxxxxxxxxxxxbxxt" +
    "txxxxxxxxcuxxxbxxcuxxxxxxcuxxxxxxcuxxxxt" +
    "txxxxxxxxccxxxbxxccxxxxxxccxxxxxxccxbxxt" +
    "txxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxt" +
    "txxxbxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxbxxxt" +
    "txxxbxxxxxbxxxxxxxxxxxxxxxxxxxxxxxxxxxxt" +
    "txxxxxxbxxxxxxxxxxxbxxxxxxxxxxxxxxxxxxbt" +
    "txxxxxxxxxxxbxxxxxxxbxxxxxxxxxxxxxxxxxxt" +
    "txxbxxxxxxxxxxxxxxbxxxxxxxxxxxxxxxxxxxxt" +
    "txxxxxxxxxxxxxxxxxxxxxbxxxxxxxxxbxxxxxxt" +
    "txxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxbxxbxxt" +
    "txxxxbxxxxxxbxbbxxxxxxxxxxxxxxxxxxbxxxxt" +
    "txxxxxxxxxxxbxbbxxxxxxxxxbxxbxbxxxxxxxet" +
    "tttttttttttttttttttttttttttttttttttttttt",
  e_1:
    "4-50-90;" +
    "tttttttttttttttttttttttttttttttttttttttt" +
    "tsxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxt" +
    "txxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxt" +
    "txxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxt" +
    "txxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxt" +
    "txxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxt" +
    "txxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxt" +
    "txxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxt" +
    "txxxxxxxccfxxxxxccfxxxxxccfxxxxxccfxxxxt" +
    "txxxxxxxcccxxxxxcccxxxxxcccxxxxxcccxxxxt" +
    "txxxxxxxcdcxxxxxcdcxxxxxcdcxxxxxcdcxxxxt" +
    "txxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxt" +
    "txxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxt" +
    "txxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxt" +
    "txxxxxxxccfxxxxxccfxxxxxccfxxxxxccfxxxxt" +
    "txxxxxxxcccxxxxxcccxxxxxcccxxxxxcccxxxxt" +
    "txxxxxxxcdcxxxxxcdcxxxxxcdcxxxxxcdcxxxxt" +
    "txxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxt" +
    "txxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxt" +
    "txxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxt" +
    "txxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxe" +
    "tttttttttttttttttttttttttttttttttttttttt",
  f_1:
    "4-40-60;" +
    "tttttttttttttttttttttttttttttttttttttttt" +
    "twwwwwwwwwxxxxbxbxxbxxxxxxxxbxwwwwwwwwwt" +
    "twccccccccxxxxxxxxxxxbxxxxbxxxccccccccwt" +
    "twcdjcccccxxbxxxxxxxxxxbxxxbxxcccccjdcwt" +
    "twwwwwwwwwxxbxxxxxxxxbxxxxxxbxwwwwwwwwwt" +
    "twccccccccxxxxxxbxxxbxxxxxxxbxccccccccwt" +
    "twcdjcccccxxxxbxxxxxxbxbbxxxxxcccccjdcwt" +
    "twwwwwwwwwxbbxxxxxxxxbxbbxxxxxwwwwwwwwwt" +
    "twccccccccxxxxbxbxxxxbxxbxxxxxccccccccwt" +
    "twcdjcccccxxxxbxbxxxxbxxbxxbxxcccccjdcwt" +
    "twwwwwwwwwxbbxbxxbxxxxbxxxbxxxwwwwwwwwwt" +
    "twccccccccxbbxbxxbxxxxxxxxxxxxccccccccwt" +
    "twcdjcccccxxxxbxxbxxxxxxxxbxxxcccccjdcwt" +
    "twwwwwwwwwxxxxxbxxxbxxxxbxxbxxwwwwwwwwwt" +
    "txxxxbxbxxbxxxxxxxxbxxxxxbxxxxxxxxxxxxbt" +
    "txxxxxxbxxxxbxxxxbxxbxbxxxbxxbxxxxxxxxxt" +
    "txxbxxxxbxxxxxbxxxbxxxxxxxbxxbxxxxxxxxxt" +
    "txxbxxxxxxxxbxxxxxxbxbbxxxxxxxxxbxxxxxxt" +
    "tbxsxxxbxxxxxxxxxxxbxbbxxxxxxxxxbbxxbxet" +
    "txxxxbxxxxxxbxbbxxxxxxbxxxxxxxxbxxbxxxxt" +
    "tbbxxxxxxxxxbxbbxxxxxxxxxbxxbxbxbxxbxxxt" +
    "tttttttttttttttttttttttttttttttttttttttt",
  g_1:
    "15-10-20;" +
    "tttttttttttttttttttttttttttttttttttttttt" +
    "txcxxcxbbxxxxxcxxbxcsxxxxcbbcbxxbxcxccxt" +
    "tcxxbxcxxcxccxxxxcxbxbxcxxxccbxxbxdxxcxt" +
    "tbxxxxxccxfxccxxxcxbxbxcxxxcwwwwwwwwwwwt" +
    "txbxdxxxcxccxxxxxxcxxbbxxbxxxxcxcxxxcxct" +
    "twwwwwwwwwwwwxbxcxxcccbxxcxxxxcxxxbxxxxe" +
    "tbxcbxxxxxxcxxbxcxxxcxxbxccxxbxccfxxxxxt" +
    "tbxcbxxxxxxcxxcbxxbxxxxcxxxbxxxxxxbxbbxt" +
    "txxxcxxbccxxxcxxbxccxxbxccxxxcxxxxbxbbxt" +
    "txxxcxxbxcxbxxxxcxxxfxxxxxxbxbxxccbxxbxt" +
    "tccxxcbxxxxcxxbxbxxxxcxccxxxxxxxccdxxcxt" +
    "txcxxxcxxcxccxxcxccxxxxxbbcbxxbxcxcbxxct" +
    "txxcdxxbxbxxxxcxccxxxxxxbccbxxbxcxccxxxt" +
    "txbxccxxbxccxxxcxbxbxcxxxccbxxcxxxxcxxxt" +
    "txxxxccxbxccxxxcxbxbxcxbxcxcbxxcbxxxxcxt" +
    "txccxxxxcxxxxccxxcbcbxxbxxxxcxxxbxxxcxbt" +
    "txxxxxcxccxbbxcxxxccbxxcxbxxxcbxxbxbxxxt" +
    "tcbxxxxxxcxxbxcxbxxxxcxccxxbxccbxxxxxxxt" +
    "tcbxxxxxxcxxcbxxbxxxxcxxxbxxxxxxbxbbxxxt" +
    "txcxxbxcxxxcxxbxccxaxxccxxxcxxxxbxbbxxxt" +
    "txcxdbfxxbxxxxcxxxbxxxxxxbxbfxxxxxdbxxxt" +
    "tttttttttttttttttttttttttttttttttttttttt",
  t_1:
    "10-10;" +
    "tttttttttttttttttttttttttttttttttttttttt" +
    "txxxxxxxxxxxxxxxxbxxxxxxxxxxxxxxxxxxxxxt" +
    "txxxxsxxxxxxxxxxxcxxxxxxxxxxxxxxxxxxxxxt" +
    "txxxxexxxxxxxxxxxcxxxxxxxxxxxxxxxxxxxxxt" +
    "txbbbbbbbbbbbxxxxcxxxxxxxxxxxxxxxxxxxxxt" +
    "tbxxxxxxxxxxxbxxxcxxxxxxxxxxxxxxxxxxxxxt" +
    "tbxxxxaxuxuxxxbxxuxxxxxxxxxxxxxxxxxxxxxt" +
    "tbxxxxxxxxxxbbxxxxxxxxxxxxxxxxxxxxxxxxxt" +
    "txbbbbbbcccbxxxxxxxxxxxxxxxxxxxxxxxxxxxt" +
    "txxxxxxxcccxxxxxxxxxxxxxxxxxxxxxxxxxxxxt" +
    "txxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxt" +
    "txxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxt" +
    "txxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxt" +
    "txxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxt" +
    "txxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxt" +
    "txxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxt" +
    "txxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxt" +
    "txxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxt" +
    "txxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxt" +
    "txxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxt" +
    "txxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxt" +
    "tttttttttttttttttttttttttttttttttttttttt",
  t_2:
    "10-10;" +
    "tttttttttttttttttttttttttttttttttttttttt" +
    "txxxxxxxxxxxxxxxxbxxxxxxxxxxxxxxxxxxxxxt" +
    "txxxxsxxxxxxxxxxxcxxxxxxxxxxxxxxxxxxxxxt" +
    "txxxxexxxxxxxxxxxcxxxxxxxxxxxxxxxxxxxxxt" +
    "txbbbbbbbbbbbxxxxcxxxxxxxxxxxxxxxxxxxxxt" +
    "tbxxxxxxxxxxxbxxxcxxxxxxxxxxxxxxxxxxxxxt" +
    "tbxxxxaxuxuxxxbxxuxxxxxxxxxxxxxxxxxxxxxt" +
    "tbxxxxxxxxxxbbxxxxxxxxxxxxxxxxxxxxxxxxxt" +
    "txbbbbbbcccbxxxxxxxxxxxxxxxxxxxxxxxxxxxt" +
    "txxxxxxxcccxxxxxxxxxxxxxxxxxxxxxxxxxxxxt" +
    "txxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxt" +
    "txxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxt" +
    "txxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxt" +
    "txxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxt" +
    "txxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxt" +
    "txxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxt" +
    "txxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxt" +
    "txxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxt" +
    "txxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxt" +
    "txxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxt" +
    "txxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxt" +
    "tttttttttttttttttttttttttttttttttttttttt",
};
